---
  - name: Instalar y configurar WordPress en Ubuntu
    hosts: all
    become: yes
    tasks:
      - name: Actualizar paquetes
        apt:
          update_cache: yes
          upgrade: yes
  
      - name: Instalar Apache, PHP y dependencias necesarias
        apt:
          name:
            - apache2
            - php
            - php-mysql
            - wget
          state: present
  
      - name: Iniciar y habilitar Apache
        service:
          name: apache2
          state: started
          enabled: yes
  
      - name: Descargar WordPress
        get_url:
          url: https://wordpress.org/latest.tar.gz
          dest: /tmp/latest.tar.gz
  
      - name: Extraer WordPress
        unarchive:
          src: /tmp/latest.tar.gz
          dest: /tmp/
          remote_src: yes
  
      - name: Copiar archivos de WordPress a /var/www/html
        shell: cp -r /tmp/wordpress/* /var/www/html/
        args:
          executable: /bin/bash
  
      - name: Eliminar la página por defecto de Apache
        file:
          path: /var/www/html/index.html
          state: absent
  
      - name: Configurar wp-config.php para usar RDS
        shell: |
          cp /var/www/html/wp-config-sample.php /var/www/html/wp-config.php
          sed -i "s/database_name_here/{{ db_name }}/" /var/www/html/wp-config.php
          sed -i "s/username_here/{{ db_username }}/" /var/www/html/wp-config.php
          sed -i "s/password_here/{{ db_password }}/" /var/www/html/wp-config.php
          sed -i "s/localhost/{{ db_endpoint }}/" /var/www/html/wp-config.php
        args:
          executable: /bin/bash
  
      - name: Ajustar permisos de /var/www/html
        file:
          path: /var/www/html
          owner: www-data
          group: www-data
          recurse: yes
  